In [51]:
import numpy as np

# Assuming you have the following lists
points_x = np.array([0.5, 0.2, 0.8, 0.6, 0.4, 0.7, 0.3, 0.9])
points_y = np.array([0.1, 0.4, 0.6, 0.9, 0.2, 0.5, 0.8, 0.3])
points_z = np.array([0.7, 0.3, 0.9, 0.4, 0.8, 0.5, 0.2, 0.6])
triangle_list = [[0, 1, 2], [3, 4, 5], [6, 7, 0], [1, 3, 5]]
quad_list = [[0, 1, 2, 3], [4, 5, 6, 7]]
marker_list = [200, 200, 200, 400, 500, 200]  # Example with extended marker list

# Combine x, y, z coordinates into a single array
points_xyz = np.column_stack((points_x, points_y, points_z))
points_xyz

array([[0.5, 0.1, 0.7],
       [0.2, 0.4, 0.3],
       [0.8, 0.6, 0.9],
       [0.6, 0.9, 0.4],
       [0.4, 0.2, 0.8],
       [0.7, 0.5, 0.5],
       [0.3, 0.8, 0.2],
       [0.9, 0.3, 0.6]])

In [52]:
# Create a dictionary to map unique points to their indices and markers
unique_points = {}
unique_markers = {}

In [53]:
# Iterate over triangle list and marker list
for triangle, marker in zip(triangle_list, marker_list[:len(triangle_list)]):
    points_triangle = points_xyz[triangle]
    for point in points_triangle:
        point_key = tuple(np.append(point,marker))
        if point_key not in unique_points:
            unique_points[point_key] = len(unique_points)
            unique_markers[point_key] = marker
unique_markers

{(0.5, 0.1, 0.7, 200.0): 200,
 (0.2, 0.4, 0.3, 200.0): 200,
 (0.8, 0.6, 0.9, 200.0): 200,
 (0.6, 0.9, 0.4, 200.0): 200,
 (0.4, 0.2, 0.8, 200.0): 200,
 (0.7, 0.5, 0.5, 200.0): 200,
 (0.3, 0.8, 0.2, 200.0): 200,
 (0.9, 0.3, 0.6, 200.0): 200,
 (0.2, 0.4, 0.3, 400.0): 400,
 (0.6, 0.9, 0.4, 400.0): 400,
 (0.7, 0.5, 0.5, 400.0): 400}

In [54]:
# Iterate over quad list and marker list
for quad, marker in zip(quad_list, marker_list[len(triangle_list):]):
    points_quad = points_xyz[quad]
    for point in points_quad:
        point_key = tuple(np.append(point,marker))
        if point_key not in unique_points:
            unique_points[point_key] = len(unique_points)
            unique_markers[point_key] = marker

In [55]:
# Create a new array to store unique points and markers
unique_array = np.zeros((len(unique_points), 4))  # Assuming 3D points and 1 marker value
unique_array[:, :] = np.array(list(unique_points.keys()))

In [56]:
# Remove duplicate points with same markers
_, unique_indices = np.unique(unique_array[:, :], axis=0, return_index=True)
unique_array = unique_array[unique_indices]

print(unique_array)

[[2.e-01 4.e-01 3.e-01 2.e+02]
 [2.e-01 4.e-01 3.e-01 4.e+02]
 [2.e-01 4.e-01 3.e-01 5.e+02]
 [3.e-01 8.e-01 2.e-01 2.e+02]
 [4.e-01 2.e-01 8.e-01 2.e+02]
 [5.e-01 1.e-01 7.e-01 2.e+02]
 [5.e-01 1.e-01 7.e-01 5.e+02]
 [6.e-01 9.e-01 4.e-01 2.e+02]
 [6.e-01 9.e-01 4.e-01 4.e+02]
 [6.e-01 9.e-01 4.e-01 5.e+02]
 [7.e-01 5.e-01 5.e-01 2.e+02]
 [7.e-01 5.e-01 5.e-01 4.e+02]
 [8.e-01 6.e-01 9.e-01 2.e+02]
 [8.e-01 6.e-01 9.e-01 5.e+02]
 [9.e-01 3.e-01 6.e-01 2.e+02]]


# Faster version

In [74]:
import numpy as np

# Assuming you have the following lists
points_x = np.array([0.5, 0.2, 0.8, 0.6, 0.4, 0.7, 0.3, 0.9])
points_y = np.array([0.1, 0.4, 0.6, 0.9, 0.2, 0.5, 0.8, 0.3])
points_z = np.array([0.7, 0.3, 0.9, 0.4, 0.8, 0.5, 0.2, 0.6])
points_tri = [[0, 1, 2], [3, 4, 5], [6, 7, 0], [1, 3, 5]]
points_quad = [[0, 1, 2, 3], [4, 5, 6, 7]]
marker_list = [200, 200, 200, 400, 500, 200]

# Combine x, y, z coordinates into a single array
points_xyz = np.column_stack((points_x, points_y, points_z))

# Combine triangle and quad indices into a single list
points_indices = points_tri + points_quad

# Combine marker_list for triangle and quad
combined_marker_list = marker_list[:len(points_tri)] + marker_list[len(points_tri):]

# Create a structured array to store unique points and markers
dtype = [('x', float), ('y', float), ('z', float), ('marker', int)]
unique_array = np.empty(0, dtype=dtype)

# Iterate over indices and marker_list simultaneously
for indices, marker in zip(points_indices, combined_marker_list):
    points_indices = points_xyz[indices]
    unique_points = np.empty(len(indices), dtype=dtype)
    unique_points['x'] = points_indices[:, 0]
    unique_points['y'] = points_indices[:, 1]
    unique_points['z'] = points_indices[:, 2]
    unique_points['marker'] = marker
    unique_array = np.append(unique_array, unique_points)

# Remove duplicate points with same markers
_, unique_indices = np.unique(unique_array[['x', 'y', 'z', 'marker']], return_index=True)
unique_array = unique_array[unique_indices]

print(unique_array)

[(0.2, 0.4, 0.3, 200) (0.2, 0.4, 0.3, 400) (0.2, 0.4, 0.3, 500)
 (0.3, 0.8, 0.2, 200) (0.4, 0.2, 0.8, 200) (0.5, 0.1, 0.7, 200)
 (0.5, 0.1, 0.7, 500) (0.6, 0.9, 0.4, 200) (0.6, 0.9, 0.4, 400)
 (0.6, 0.9, 0.4, 500) (0.7, 0.5, 0.5, 200) (0.7, 0.5, 0.5, 400)
 (0.8, 0.6, 0.9, 200) (0.8, 0.6, 0.9, 500) (0.9, 0.3, 0.6, 200)]


In [79]:
import numpy as np

# Assuming you have the following lists
points_x = np.array([0.5, 0.2, 0.8, 0.6, 0.4, 0.7, 0.3, 0.9])
points_y = np.array([0.1, 0.4, 0.6, 0.9, 0.2, 0.5, 0.8, 0.3])
points_z = np.array([0.7, 0.3, 0.9, 0.4, 0.8, 0.5, 0.2, 0.6])
points_tri = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 0], [1, 3, 5]])
points_quad = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
marker_list = np.array([200, 200, 200, 400, 500, 200])

# Combine x, y, z coordinates into a single array
points_xyz = np.column_stack((points_x, points_y, points_z))

# Create a new array to store combined indices
num_triangles = len(points_tri)
num_quads = len(points_quad)
total_triangles = num_triangles + num_quads
points_indices = np.full((total_triangles, 4), -1, dtype=int)
points_indices[:num_triangles, :3] = points_tri
points_indices[num_triangles:, :] = points_quad

# Combine marker_list for triangle and quad
combined_marker_list = np.concatenate((marker_list[:num_triangles], marker_list[num_triangles:]))

# Create a structured array to store unique points and markers
dtype = [('x', float), ('y', float), ('z', float), ('marker', int)]
unique_array = np.empty(0, dtype=dtype)

# Iterate over indices and marker_list simultaneously
for indices, marker in zip(points_indices, combined_marker_list):
    if -1 in indices:
        indices = indices[:-1]
    points_indices = points_xyz[indices]
    unique_points = np.empty(len(indices), dtype=dtype)
    unique_points['x'] = points_indices[:, 0]
    unique_points['y'] = points_indices[:, 1]
    unique_points['z'] = points_indices[:, 2]
    unique_points['marker'] = marker
    unique_array = np.append(unique_array, unique_points)

# Remove duplicate points with same markers
_, unique_indices = np.unique(unique_array[['x', 'y', 'z', 'marker']], return_index=True)
unique_array = unique_array[unique_indices]

print(unique_array)

[(0.2, 0.4, 0.3, 200) (0.2, 0.4, 0.3, 400) (0.2, 0.4, 0.3, 500)
 (0.3, 0.8, 0.2, 200) (0.4, 0.2, 0.8, 200) (0.5, 0.1, 0.7, 200)
 (0.5, 0.1, 0.7, 500) (0.6, 0.9, 0.4, 200) (0.6, 0.9, 0.4, 400)
 (0.6, 0.9, 0.4, 500) (0.7, 0.5, 0.5, 200) (0.7, 0.5, 0.5, 400)
 (0.8, 0.6, 0.9, 200) (0.8, 0.6, 0.9, 500) (0.9, 0.3, 0.6, 200)]
